
API_KEY : '6fb6f450afe54286809a128c753a6a3d'
EXCEL_FILE : 'employees list for task.xlsx'
INCOME_YEAR : 2021
TABLE_DESC : "Inhabitants' disposable monetary income"
BASE_URL : "https://pxnet2.stat.fi:443/PXWeb/api/v1/en/Postinumeroalueittainen_avoin_tieto"

HQ_LONGITUDE : 24.832262981061717
HQ_LATITUDE : 60.18056015

# db connection configs
USR : 'postgres'
PWD : 'Ghtn47es592'
ADDRESS : 'localhost'
PORT : 5432
DATABASE : 'postgres_test2'